# Generated by Django 3.1.4 on 2021-03-04 13:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom', models.CharField(blank=True, max_length=50, null=True)),
                ('bride', models.CharField(blank=True, max_length=50, null=True)),
                ('groom_image', models.ImageField(upload_to='uploads/', verbose_name='image')),
                ('bride_image', models.ImageField(upload_to='uploads/', verbose_name='image')),
                ('descrption', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
